# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
arm_controller:
  ros__parameters:
    joints:
      - manipulator/joint_1
      - manipulator/joint_2
      - manipulator/joint_3
      - manipulator/joint_4
      - manipulator/joint_5
      - manipulator/joint_6
    write_op_modes:
      - manipulator/joint_1
      - manipulator/joint_2
      - manipulator/joint_3
      - manipulator/joint_4
      - manipulator/joint_5
      - manipulator/joint_6
