# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
controller_list:
  - name: fake_manipulator_controller
    type: interpolate
    joints:
      - manipulator/joint_1
      - manipulator/joint_2
      - manipulator/joint_3
      - manipulator/joint_4
      - manipulator/joint_5
      - manipulator/joint_6
  - name: fake_gripper_controller
    type: interpolate
    joints:
      - eef_joint_finger_1
      - eef_joint_finger_2