# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  eef_joint_finger_1:
    has_velocity_limits: true
    max_velocity: 0.0001
    has_acceleration_limits: true
    max_acceleration: 3.75
    has_jerk_limits: false
  eef_joint_finger_2:
    has_velocity_limits: true
    max_velocity: 0.0001
    has_acceleration_limits: true
    max_acceleration: 3.75
    has_jerk_limits: false
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.5 # 2.0
    has_acceleration_limits: true
    max_acceleration: 1.0 # 3.75
    has_jerk_limits: false
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
  joint_6:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: false
