global:
  huggingface:
    apiToken: 
  proxy:
    no_proxy: 
    http_proxy: 
    https_proxy:

  # llmName is the Large Language Model used by OVMS
  llmName: ""

  egai_ovms_pvc:
    size: 40Gi
    
ovms:
  name: ovms
  image:
    repository: openvino/model_server
    tag: "2025.1"
    pullPolicy: IfNotPresent
  readinessProbe:
    httpGet:
      path: /v2/health/ready
      port: 8300
    initialDelaySeconds: 60
    periodSeconds: 30
  service:
    type: ClusterIP
    port: 8300
    targetPort: 8300
  
  # scriptconfigmap: ovms-configmap.yaml
  env:
    WEIGHT_FORMAT: "fp16"
    model_directory_name: "converted_model"
  script:
    name: "ovms-model-preparation"
