# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint1
    - joint2
