# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    write_op_modes:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
