# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  default: True
  type: FollowJointTrajectory
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
