# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
# Limits for the Pilz planner
cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  max_trans_dec: -5.0
  max_rot_vel: 1.57
