# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    jaka_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_controller:
      type: joint_state_controller/JointStateController

jaka_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
