# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
controller_names:
  - jaka_arm_controller

jaka_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6