# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
jaka_arm:
  # kinematics_solver: pick_ik/PickIkPlugin
  # kinematics_solver_timeout: 0.05
  # kinematics_solver_attempts: 3
  # mode: global
  # position_scale: 1.0
  # rotation_scale: 0.5
  # position_threshold: 0.001
  # orientation_threshold: 0.1
  # cost_threshold: 0.001
  # minimal_displacement_weight: 0.001
  # gd_step_size: 0.0001
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005